"""Installability contract for the optional abacuslite parser dependency.

The canonical checkout is a Stage 0 oracle, not an installable dependency.
This test keeps the Stage 1 boundary executable without claiming that a
published abacuslite release exists.
"""

from __future__ import annotations

import os
import json
from pathlib import Path
import re
import tomllib
import zipfile
from email.parser import Parser

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

import pytest


ROOT = Path(__file__).resolve().parents[1]
PROVENANCE = ROOT / "docs/superpowers/evidence/2026-09-14-forge-stage1-package-provenance.json"


def _project_metadata() -> dict[str, object]:
    with (ROOT / "pyproject.toml").open("rb") as stream:
        return tomllib.load(stream)["project"]


def test_local_source_wheel_provenance_is_an_explicit_oracle_binding() -> None:
    """Bind every local oracle wheel to its source and candidate revision."""

    record = json.loads(PROVENANCE.read_text(encoding="utf-8"))
    assert record["schema_version"] == "forge.stage1-package-provenance/v1"
    assert record["status"] == "local_oracle_only"
    assert record["public_exact_release_available"] is False
    assert record["forge_optional_extra_declared"] is False

    source = record["canonical_source"]
    assert re.fullmatch(r"[0-9a-f]{40}", source["commit"])
    assert source["package_name"] == "abacuslite"
    assert source["package_version"] == "1.0.0"
    assert source["wheel_filename"] == "abacuslite-1.0.0-py3-none-any.whl"
    assert re.fullmatch(r"[0-9a-f]{64}", source["wheel_sha256"])
    assert "pip wheel" in source["build_command"]
    assert "--no-deps" in source["build_command"]

    forge = record["forge_candidate"]
    assert re.fullmatch(r"[0-9a-f]{40}", forge["revision"])
    assert forge["package_name"] == "abacus-forge"
    assert forge["package_version"] == "0.1.0"
    assert forge["wheel_filename"] == "abacus_forge-0.1.0-py3-none-any.whl"
    assert re.fullmatch(r"[0-9a-f]{64}", forge["wheel_sha256"])
    assert "pip wheel" in forge["build_command"]
    assert "--no-deps" in forge["build_command"]

    assert source["artifact_binding"] == {
        "canonical_commit": source["commit"],
        "wheel_filename": source["wheel_filename"],
        "wheel_sha256": source["wheel_sha256"],
    }
    assert forge["artifact_binding"] == {
        "forge_revision": forge["revision"],
        "wheel_filename": forge["wheel_filename"],
        "wheel_sha256": forge["wheel_sha256"],
    }


def test_abacuslite_extra_is_exactly_pinned_if_declared() -> None:
    project = _project_metadata()
    dependencies = project.get("dependencies", [])
    optional = project.get("optional-dependencies", {})
    assert isinstance(dependencies, list)
    assert not any(str(item).lower().startswith("abacuslite") for item in dependencies)
    assert isinstance(optional, dict)

    declared = [
        str(item)
        for values in optional.values()
        if isinstance(values, list)
        for item in values
        if str(item).lower().startswith("abacuslite")
    ]
    if not declared:
        # No public exact release is currently available.  The optional
        # parser therefore remains deliberately blocked at the package layer.
        return
    assert len(declared) == 1
    assert re.fullmatch(r"abacuslite==[^;\s]+", declared[0], flags=re.IGNORECASE)


def test_built_wheel_keeps_the_same_optional_dependency_boundary() -> None:
    """Check built metadata when a release candidate wheel is supplied.

    Source metadata and wheel metadata are generated by different layers of
    the build backend.  This opt-in check makes the Stage 1 package gate
    executable against the exact wheel that is about to be reviewed without
    requiring every ordinary test run to build or download a wheel.
    """

    wheel_value = os.environ.get("ABACUS_FORGE_WHEEL")
    if not wheel_value:
        pytest.skip("set ABACUS_FORGE_WHEEL to inspect a release candidate wheel")
    wheel = Path(wheel_value).expanduser().resolve()
    assert wheel.is_file(), wheel

    with zipfile.ZipFile(wheel) as archive:
        metadata_paths = [
            name
            for name in archive.namelist()
            if name.endswith(".dist-info/METADATA")
        ]
        assert len(metadata_paths) == 1
        metadata = archive.read(metadata_paths[0]).decode("utf-8")

    names = [
        line.split(":", 1)[1].strip()
        for line in metadata.splitlines()
        if line.startswith("Name:")
    ]
    assert names == ["abacus-forge"]

    requires = [
        line.split(":", 1)[1].strip()
        for line in metadata.splitlines()
        if line.startswith("Requires-Dist:")
    ]
    abacuslite = [
        requirement
        for requirement in requires
        if re.match(r"^abacuslite(?:\s|[<>=!~;]|$)", requirement, flags=re.IGNORECASE)
    ]
    assert not any(
        requirement.lower().startswith("abacuslite") and "; extra" not in requirement.lower()
        for requirement in requires
    ), "abacuslite must not enter the default wheel dependencies"
    if abacuslite:
        assert len(abacuslite) == 1
        assert re.fullmatch(
            r"abacuslite==[^;\s]+;\s*extra\s*==\s*['\"][^'\"]+['\"]",
            abacuslite[0],
            flags=re.IGNORECASE,
        )


    # Bind the generated artifact to the source declaration, not merely to a
    # syntactically acceptable optional requirement in either file.
    project = _project_metadata()
    assert names == [project["name"]]
    headers = Parser().parsestr(metadata)
    assert headers.get_all("Version", []) == [project["version"]]
    optional = project.get("optional-dependencies", {})
    expected_extras = {canonicalize_name(extra) for extra in optional}
    actual_extras = [canonicalize_name(extra) for extra in headers.get_all("Provides-Extra", [])]
    assert len(actual_extras) == len(set(actual_extras))
    assert set(actual_extras) == expected_extras

    expected_parser = []
    for extra, dependencies in optional.items():
        for dependency in dependencies:
            requirement = Requirement(dependency)
            if canonicalize_name(requirement.name) == "abacuslite":
                assert re.fullmatch(r"abacuslite==[^;\s*]+", dependency, flags=re.IGNORECASE)
                expected_parser.append((str(requirement.specifier), canonicalize_name(extra)))
    assert len(expected_parser) <= 1
    assert all(canonicalize_name(Requirement(item).name) != "abacuslite"
               for item in project.get("dependencies", []))

    actual_parser = []
    for dependency in requires:
        requirement = Requirement(dependency)
        if canonicalize_name(requirement.name) != "abacuslite":
            continue
        marker = re.fullmatch(r"extra == [\"']([^\"']+)[\"']", str(requirement.marker))
        assert marker is not None, "abacuslite must be scoped to exactly one extra"
        assert requirement.url is None and not requirement.extras
        actual_parser.append((str(requirement.specifier), canonicalize_name(marker[1])))
    assert actual_parser == expected_parser, "source/wheel abacuslite dependency drift"
