"""Installability contract for the optional abacuslite parser dependency.

The canonical checkout is a Stage 0 oracle, not an installable dependency.
This test keeps the Stage 1 boundary executable without claiming that a
published abacuslite release exists.
"""

from __future__ import annotations

import os
from pathlib import Path
import re
import tomllib
import zipfile

import pytest


ROOT = Path(__file__).resolve().parents[1]


def _project_metadata() -> dict[str, object]:
    with (ROOT / "pyproject.toml").open("rb") as stream:
        return tomllib.load(stream)["project"]


def test_abacuslite_extra_is_exactly_pinned_if_declared() -> None:
    project = _project_metadata()
    dependencies = project.get("dependencies", [])
    optional = project.get("optional-dependencies", {})
    assert isinstance(dependencies, list)
    assert not any(str(item).lower().startswith("abacuslite") for item in dependencies)
    assert isinstance(optional, dict)

    declared = [
        str(item)
        for values in optional.values()
        if isinstance(values, list)
        for item in values
        if str(item).lower().startswith("abacuslite")
    ]
    if not declared:
        # No public exact release is currently available.  The optional
        # parser therefore remains deliberately blocked at the package layer.
        return
    assert len(declared) == 1
    assert re.fullmatch(r"abacuslite==[^;\s]+", declared[0], flags=re.IGNORECASE)


def test_built_wheel_keeps_the_same_optional_dependency_boundary() -> None:
    """Check built metadata when a release candidate wheel is supplied.

    Source metadata and wheel metadata are generated by different layers of
    the build backend.  This opt-in check makes the Stage 1 package gate
    executable against the exact wheel that is about to be reviewed without
    requiring every ordinary test run to build or download a wheel.
    """

    wheel_value = os.environ.get("ABACUS_FORGE_WHEEL")
    if not wheel_value:
        pytest.skip("set ABACUS_FORGE_WHEEL to inspect a release candidate wheel")
    wheel = Path(wheel_value).expanduser().resolve()
    assert wheel.is_file(), wheel

    with zipfile.ZipFile(wheel) as archive:
        metadata_paths = [
            name
            for name in archive.namelist()
            if name.endswith(".dist-info/METADATA")
        ]
        assert len(metadata_paths) == 1
        metadata = archive.read(metadata_paths[0]).decode("utf-8")

    names = [
        line.split(":", 1)[1].strip()
        for line in metadata.splitlines()
        if line.startswith("Name:")
    ]
    assert names == ["abacus-forge"]

    requires = [
        line.split(":", 1)[1].strip()
        for line in metadata.splitlines()
        if line.startswith("Requires-Dist:")
    ]
    abacuslite = [
        requirement
        for requirement in requires
        if re.match(r"^abacuslite(?:\s|[<>=!~;]|$)", requirement, flags=re.IGNORECASE)
    ]
    assert not any(
        requirement.lower().startswith("abacuslite") and "; extra" not in requirement.lower()
        for requirement in requires
    ), "abacuslite must not enter the default wheel dependencies"
    if abacuslite:
        assert len(abacuslite) == 1
        assert re.fullmatch(
            r"abacuslite==[^;\s]+;\s*extra\s*==\s*['\"][^'\"]+['\"]",
            abacuslite[0],
            flags=re.IGNORECASE,
        )
