"""Gaussian cube data helpers for Forge property packs."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np


@dataclass(slots=True)
class CubeData:
    """Minimal Gaussian cube payload with volumetric data."""

    comments: list[str]
    natoms: int
    origin: list[float]
    grid: list[dict[str, object]]
    atom_lines: list[str]
    data: np.ndarray

    @classmethod
    def from_file(cls, path: str | Path) -> "CubeData":
        lines = Path(path).read_text(encoding="utf-8", errors="ignore").splitlines()
        if len(lines) < 6:
            raise ValueError(f"cube file is too short: {path}")
        comments = [lines[0], lines[1]]
        origin_parts = lines[2].split()
        natoms = int(float(origin_parts[0]))
        origin = [float(value) for value in origin_parts[1:4]]
        grid = []
        shape = []
        for line in lines[3:6]:
            parts = line.split()
            count = int(float(parts[0]))
            shape.append(abs(count))
            grid.append({"count": count, "vector": [float(value) for value in parts[1:4]]})
        atom_line_count = abs(natoms)
        atom_lines = lines[6 : 6 + atom_line_count]
        values: list[float] = []
        for line in lines[6 + atom_line_count :]:
            values.extend(float(token) for token in line.split())
        expected = int(np.prod(shape))
        if len(values) != expected:
            raise ValueError(f"cube data size mismatch: expected {expected}, got {len(values)}")
        return cls(
            comments=comments,
            natoms=natoms,
            origin=origin,
            grid=grid,
            atom_lines=atom_lines,
            data=np.asarray(values, dtype=float).reshape(shape),
        )

    def with_data(self, data: Iterable[float] | np.ndarray) -> "CubeData":
        array = np.asarray(data, dtype=float).reshape(self.data.shape)
        return CubeData(
            comments=list(self.comments),
            natoms=self.natoms,
            origin=list(self.origin),
            grid=[{"count": item["count"], "vector": list(item["vector"])} for item in self.grid],
            atom_lines=list(self.atom_lines),
            data=array,
        )

    def write(self, path: str | Path) -> Path:
        destination = Path(path)
        destination.parent.mkdir(parents=True, exist_ok=True)
        lines = [
            self.comments[0] if self.comments else "Forge cube",
            self.comments[1] if len(self.comments) > 1 else "Generated by abacus-forge",
            f"{self.natoms} {' '.join(_fmt(value) for value in self.origin)}",
        ]
        for item in self.grid:
            lines.append(f"{int(item['count'])} {' '.join(_fmt(value) for value in item['vector'])}")
        lines.extend(self.atom_lines)
        flat = self.data.reshape(-1)
        for start in range(0, len(flat), 6):
            lines.append(" ".join(_fmt(value) for value in flat[start : start + 6]))
        destination.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return destination


def subtract_cubes(left: str | Path | CubeData, right: str | Path | CubeData) -> CubeData:
    """Return ``left - right`` for matching cube grids."""

    left_cube = left if isinstance(left, CubeData) else CubeData.from_file(left)
    right_cube = right if isinstance(right, CubeData) else CubeData.from_file(right)
    _require_same_grid(left_cube, right_cube)
    return left_cube.with_data(left_cube.data - right_cube.data)


def add_cubes(cubes: Iterable[str | Path | CubeData]) -> CubeData:
    """Return the element-wise sum of matching cube grids."""

    iterator = iter(cubes)
    try:
        first = next(iterator)
    except StopIteration as exc:
        raise ValueError("add_cubes requires at least one cube") from exc
    total = first if isinstance(first, CubeData) else CubeData.from_file(first)
    data = total.data.copy()
    for cube_like in iterator:
        cube = cube_like if isinstance(cube_like, CubeData) else CubeData.from_file(cube_like)
        _require_same_grid(total, cube)
        data = data + cube.data
    return total.with_data(data)


def planar_average(cube: str | Path | CubeData, *, axis: int) -> list[float]:
    """Average cube data over the two axes perpendicular to ``axis``."""

    payload = cube if isinstance(cube, CubeData) else CubeData.from_file(cube)
    if axis not in {0, 1, 2}:
        raise ValueError("axis must be 0, 1, or 2")
    reduce_axes = tuple(index for index in range(3) if index != axis)
    return [float(value) for value in np.mean(payload.data, axis=reduce_axes)]


def _require_same_grid(left: CubeData, right: CubeData) -> None:
    if left.data.shape != right.data.shape:
        raise ValueError(f"cube shape mismatch: {left.data.shape} != {right.data.shape}")
    left_vectors = [item["vector"] for item in left.grid]
    right_vectors = [item["vector"] for item in right.grid]
    if not np.allclose(left_vectors, right_vectors):
        raise ValueError("cube grid vectors do not match")


def _fmt(value: object) -> str:
    return f"{float(value):.10g}"
